version: '3.7'

services:

  tmpl-react-pwa-prod:
    container_name: tmpl-react-pwa-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    stdin_open: true